### PR TITLE
Fix bug on empty multipart upload.

### LINKED ISSUE #19: Part can get uploaded twice
For some reason part might get uploaded twice. This renders the uploaded file unusable.

I stated a long recording and I was syncing to S3 once every 10 minutes. The final file ended up being corrupt. (different md5 and unplayable).
After doing some binary diffs I have noticed the following arrangement of parts:
```
Local: [p1][p2][p3][p4] ... [p53]
S3:    [p1][p1][p2][p4] ... [p53]
```

Observations:
- [p1] got uploaded twice
- [p2] got uploaded after [p1], and [p3] is missing
- the sync operation must have stopped after [p3]
- the new sync picked up the new parts correctly and ignored [p3]

### PR DESCRIPTION
**Pull request by petrabarus**
This will check if the previous multipart upload has no parts due to empty file. Fixes #19

### CODE REVIEW

File: src/main/java/tdl/s3/upload/MultipartUploadHelper.java [hunk 1]
```diff
@@ -32,11 +32,16 @@ static long getUploadedSize(PartListing partListing) {
...
-        return partListing.getParts()
+        List<PartSummary> parts = partListing.getParts();
+        if (parts.isEmpty()) { //handle previously empty upload
+            return 0;
+        } else {
+            return parts
                 .stream()
                 .mapToInt(PartSummary::getPartNumber)
                 .max()
                 .orElse(1);
```
Comment (julianghionoiu) [inline src/main/java/tdl/s3/upload/MultipartUploadHelper.java]: If we change this to 0 will this solve our problem?

File: src/test/java/tdl/s3/C_OnDemand_IncompleteFileUpload_AccTest.java [hunk 2]
```diff
@@ -160,4 +162,49 @@ public void should_be_able_to_upload_failed_parts() throws Exception {
...
+        targetSyncFolder.lock(fileName);
+
+        //synchronize folder
+        Path directoryPath = targetSyncFolder.getFolderPath();
+        Source directorySource = Source.getBuilder(directoryPath)
+                .setFilters(defaultFilters)
+                .setRecursive(true)
+                .create();
+        
+        RemoteSync directoryFirstSync = new RemoteSync(directorySource, destination);
```
Comment (julianghionoiu) [inline src/test/java/tdl/s3/C_OnDemand_IncompleteFileUpload_AccTest.java]: No need to created the RemoteSync again

File: src/test/java/tdl/s3/rules/RemoteTestBucket.java [hunk 3]
```diff
@@ -85,6 +85,21 @@ public ObjectMetadata getObjectMetadata(String key) {
                 .findAny();
     }
 
+    public List<PartSummary> getPartsForKey(String key) {
```
Comment (julianghionoiu) [inline src/test/java/tdl/s3/rules/RemoteTestBucket.java]: This can be part of `remoteTestBucket`

File: src/test/java/tdl/s3/C_OnDemand_IncompleteFileUpload_AccTest.java [hunk 4]
```diff
@@ -160,4 +162,49 @@ public void should_be_able_to_upload_failed_parts() throws Exception {
         assertTrue(remoteTestBucket.getObjectMetadata(fileName)
                 .getETag().startsWith(targetSyncFolder.getCompleteFileMD5(fileName)));
     }
+    
+    @Test
+    public void should_be_able_handle_empty_file() throws Exception {
```
Comment (julianghionoiu) [inline src/test/java/tdl/s3/C_OnDemand_IncompleteFileUpload_AccTest.java]: This test also covers `should_be_able_to_continue_incomplete_file_and_finalise` so we should keep only one.

**Comment by julianghionoiu** [comment]
I am glad the we got to the bottom of this issue.
I have left some small comments to the PR, nothing major.

We should merge this PR first before merging my other PR.

File: src/main/java/tdl/s3/upload/MultipartUploadHelper.java (hunk 1 above)
Comment (petrabarus) [inline src/main/java/tdl/s3/upload/MultipartUploadHelper.java]: I think it does.

File: src/test/java/tdl/s3/rules/RemoteTestBucket.java (hunk 3 above)
Comment (petrabarus) [inline src/test/java/tdl/s3/rules/RemoteTestBucket.java]: It's already part of RemoteTestBucket, isn't it?

**Comment by julianghionoiu** [comment]
Looks good. Can be merged.

**Comment by petrabarus** [comment]
@julianghionoiu need you to approve the PR first.

**Comment by julianghionoiu** [comment]
Forgot to approve. Done
